### ISSUE TITLE
python 3 Eddystone decoding

### ISSUE THREAD

**Issue by ccloquet** [singaCapital/BLE-Beacon-Scanner#6]
Thanks for this great piece of code!

A tiny python3 improvement:

in ScanUtility.py
on line 71
~~~url = prefix + hexUrl.decode("hex")~~~
should be replaced by smth like
~~~url = prefix + bytes.fromhex(hexUrl).decode('utf-8')~~~

**Comment by singaCapital** [comment]
Thanks @ccloquet I'm going to spend some time making a few changes. Will add this to the list.
